/*========================== begin_copyright_notice ============================

Copyright (C) 2021 Intel Corporation

SPDX-License-Identifier: MIT

============================= end_copyright_notice ===========================*/

//     File Name:  gfx_device_info.h
//
//     Abstract:   Device information for Linux.

#include "md_driver_ifc_linux_perf.h"
#include <map>

using namespace MetricsDiscovery;

namespace MetricsDiscoveryInternal
{
    std::map<int32_t, TPlatformIndexGt> platformIndexMap{
        { 0x0402, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0412, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0422, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0406, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0416, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0426, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x040A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x041A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x042A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x040B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x041B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x042B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x040E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x041E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x042E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0C02, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0C12, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0C22, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0C06, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0C16, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0C26, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0C0A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0C1A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0C2A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0C0B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0C1B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0C2B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0C0E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0C1E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0C2E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0A02, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0A12, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0A22, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0A06, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0A16, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0A26, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0A0A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0A1A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0A2A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0A0B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0A1B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0A2B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0A0E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0A1E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0A2E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0D02, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0D12, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0D22, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0D06, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0D16, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0D26, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0D0A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0D1A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0D2A, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0D0B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0D1B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0D2B, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },
        { 0x0D0E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT1 ) },
        { 0x0D1E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT2 ) },
        { 0x0D2E, SPlatformIndexGt( GENERATION_HSW, GFX_GTTYPE_GT3 ) },

        { 0x1602, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x1606, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x160A, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x160B, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x160D, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x160E, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT1 ) },
        { 0x1612, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x1616, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x161A, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x161B, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x161D, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x161E, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT2 ) },
        { 0x1622, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },
        { 0x1626, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },
        { 0x162A, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },
        { 0x162B, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },
        { 0x162D, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },
        { 0x162E, SPlatformIndexGt( GENERATION_BDW, GFX_GTTYPE_GT3 ) },

        { 0x1902, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT1 ) },
        { 0x1906, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT1 ) },
        { 0x190A, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT1 ) },
        { 0x190B, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT1 ) },
        { 0x190E, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT1 ) },
        { 0x1912, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1913, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1915, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1916, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1917, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x191A, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x191B, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x191D, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x191E, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1921, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT2 ) },
        { 0x1923, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT3 ) },
        { 0x1926, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT3 ) },
        { 0x1927, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT3 ) },
        { 0x192A, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT4 ) },
        { 0x192B, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT3 ) },
        { 0x192D, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT3 ) },
        { 0x1932, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT4 ) },
        { 0x193A, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT4 ) },
        { 0x193B, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT4 ) },
        { 0x193D, SPlatformIndexGt( GENERATION_SKL, GFX_GTTYPE_GT4 ) },

        { 0x0A84, SPlatformIndexGt( GENERATION_BXT, GFX_GTTYPE_UNDEFINED ) },
        { 0x1A84, SPlatformIndexGt( GENERATION_BXT, GFX_GTTYPE_UNDEFINED ) },
        { 0x1A85, SPlatformIndexGt( GENERATION_BXT, GFX_GTTYPE_UNDEFINED ) },
        { 0x5A84, SPlatformIndexGt( GENERATION_BXT, GFX_GTTYPE_UNDEFINED ) },
        { 0x5A85, SPlatformIndexGt( GENERATION_BXT, GFX_GTTYPE_UNDEFINED ) },

        { 0x3184, SPlatformIndexGt( GENERATION_GLK, GFX_GTTYPE_UNDEFINED ) },
        { 0x3185, SPlatformIndexGt( GENERATION_GLK, GFX_GTTYPE_UNDEFINED ) },

        { 0x5902, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x5906, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x590A, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x5908, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x590B, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x590E, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT1 ) },
        { 0x5913, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5915, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5917, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5912, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5916, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x591A, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x591B, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x591D, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x591E, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5921, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x5923, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT3 ) },
        { 0x5926, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT3 ) },
        { 0x5927, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT3 ) },
        { 0x593B, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT4 ) },
        { 0x591C, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },
        { 0x87C0, SPlatformIndexGt( GENERATION_KBL, GFX_GTTYPE_GT2 ) },

        { 0x87CA, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E90, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3E93, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3E99, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3E9C, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3E91, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E92, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E96, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E98, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E9A, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E9B, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3E94, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3EA9, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3EA5, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT3 ) },
        { 0x3EA6, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT3 ) },
        { 0x3EA7, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT3 ) },
        { 0x3EA8, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT3 ) },
        { 0x3EA1, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3EA4, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x3EA0, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3EA3, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x3EA2, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT3 ) },
        { 0x9B21, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BA0, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BA2, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BA4, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BA5, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BA8, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BAA, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BAB, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9BAC, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT1 ) },
        { 0x9B41, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC0, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC2, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC4, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC5, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC6, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BC8, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BCA, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BCB, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BCC, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BE6, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },
        { 0x9BF6, SPlatformIndexGt( GENERATION_CFL, GFX_GTTYPE_GT2 ) },

        { 0x8A50, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT2 ) },
        { 0x8A51, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT2 ) },
        { 0x8A52, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT2 ) },
        { 0x8A53, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT2 ) },
        { 0x8A54, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A56, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A57, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A58, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A59, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A5A, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A5B, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A5C, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A5D, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0x8A71, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT1 ) },
        { 0xFF05, SPlatformIndexGt( GENERATION_ICL, GFX_GTTYPE_GT2 ) },

        { 0x4500, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4541, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4551, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4555, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4557, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4571, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4E51, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4E55, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4E57, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4E61, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },
        { 0x4E71, SPlatformIndexGt( GENERATION_EHL, GFX_GTTYPE_UNDEFINED ) },

        { 0x4C8A, SPlatformIndexGt( GENERATION_RKL, GFX_GTTYPE_GT1 ) },
        { 0x4C8B, SPlatformIndexGt( GENERATION_RKL, GFX_GTTYPE_GT1 ) },
        { 0x4C8C, SPlatformIndexGt( GENERATION_RKL, GFX_GTTYPE_GT1 ) },
        { 0x4C90, SPlatformIndexGt( GENERATION_RKL, GFX_GTTYPE_GT1 ) },
        { 0x4C9A, SPlatformIndexGt( GENERATION_RKL, GFX_GTTYPE_GT1 ) },

        { 0x46A0, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46A1, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46A2, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46A3, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46A6, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46A8, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46AA, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x4626, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x4628, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x462A, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46B0, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46B1, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46B2, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46B3, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46C0, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46C1, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46C2, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },
        { 0x46C3, SPlatformIndexGt( GENERATION_ADLP, GFX_GTTYPE_GT2 ) },

        { 0x9A40, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9A49, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9A59, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9A60, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT1 ) },
        { 0x9A68, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT1 ) },
        { 0x9A70, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT1 ) },
        { 0x9A78, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9AC0, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9AC9, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9AD9, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },
        { 0x9AF8, SPlatformIndexGt( GENERATION_TGL, GFX_GTTYPE_GT2 ) },

        { 0x4905, SPlatformIndexGt( GENERATION_DG1, GFX_GTTYPE_UNDEFINED ) },
        { 0x4906, SPlatformIndexGt( GENERATION_DG1, GFX_GTTYPE_UNDEFINED ) },
        { 0x4907, SPlatformIndexGt( GENERATION_DG1, GFX_GTTYPE_UNDEFINED ) },
        { 0x4908, SPlatformIndexGt( GENERATION_DG1, GFX_GTTYPE_UNDEFINED ) },
    };

    std::map<GTDI_PLATFORM_INDEX, uint32_t> threadsPerEuMap{
        { GENERATION_HSW, 7 },
        { GENERATION_BDW, 7 },
        { GENERATION_SKL, 7 },
        { GENERATION_BXT, 6 },
        { GENERATION_KBL, 7 },
        { GENERATION_GLK, 6 },
        { GENERATION_ICL, 7 },
        { GENERATION_TGL, 7 },
        { GENERATION_CFL, 7 },
        { GENERATION_EHL, 7 },
        { GENERATION_DG1, 7 },
        { GENERATION_RKL, 7 },
        { GENERATION_ADLP, 7 },
    };

} // namespace MetricsDiscoveryInternal
